# sno.yaml - test message to trigger synch#
apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  name: "bos2ipv4sno"
  namespace: "bos2ipv4sno"
spec:
  baseDomain: "workload.bos2.lab"
  automatedCleaningMode: "metadata"
  pullSecretRef:
    name: "assisted-deployment-pull-secret-ipv4"
  #clusterImageSetNameRef: "img4.11.7-x86-64-appsub"
  clusterImageSetNameRef: "img4.9.37-x86-64-appsub"
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCtSAUavTTr4dTvMOqZ/A6mg9q++qrVSNIu3vICnGUPpKGmQk4227TlaL9iwBkBqbGMvOaBZwn/b3URk/QE/El5ElzqaNNJxHqxWHGNKOJB49sVj5f57Usw07WyMy8CDy0Hk701jzvrdxqckfMEmMzWjE0C7Zpus6J3GyG3ANTYbSQGRtzdz7bcg05Xm0xCzfC/HAEF6Arz/cTv9k9rioiu1reV1qqq+FAlnKx3x/+XsG5cHMhnVuUnOU59p9pOh+v/nxq5Ysz/5iJrKNmJqkUAPShrfs3Kk2Z8TJVoEKoyyfme4uNAqBg2xZjnaPf8avfmc8uYzjHN7BA4w1fMw/mO71FCXkuxukttUeoqO2ARpofwzIeiH2wmJ7fKLaomETbZyIzYiVoZM2VKu1nPNmWOluqrpvNBnufWLpmRqWntmvT26IEGmlAjTz1HV0VZXVo+6viI3RQTJJXeZ7uTjCPz/uVsrv5U2BthWIkJ7OJEB0mcwbSJF5FOhML8dZ+/ODc= mjanardh@mjanardh.remote.csb"
  clusters:
  - clusterName: "bos2ipv4sno"
    networkType: "OVNKubernetes"
    #clusterType: "sno"
    #clusterProfile: "du"
    clusterLabels:
      group-du-sno: ""
      common: true
      sites : "sno"
    clusterNetwork:
      - cidr: 10.128.0.0/14
        hostPrefix: 23
    machineNetwork:
      - cidr: 192.168.18.0/25
    serviceNetwork:
      - 172.16.0.0/16
    additionalNTPSources:
      - 2.rhel.pool.ntp.org
    nodes:
      - hostName: "bos2ipv4sno.workload.bos2.lab"
        role: "master"
        automatedCleaningMode: "metadata"
        bmcAddress: "redfish-virtualmedia://192.168.18.15:8080/redfish/v1/Systems/04dd11d1-f1da-4969-8555-36d8930163a7"
        bmcCredentialsName: 
          name: "ipv4-bmc-secret"
        bmc:
          disableCertificateVerification: "true"        
        bootMACAddress: "52:54:00:ac:12:66"
        bootMode: "UEFI"
        rootDeviceHints:
          deviceName: "/dev/vda"
        cpuset: "0-1,9-12,14-15"
        nodeNetwork:
          interfaces:
            - name: enp1s0
              macAddress: "52:54:00:ac:12:66"
          config:
            interfaces:
              - name: enp1s0
                type: ethernet
                state: up
                macAddress: "52:54:00:ac:12:66"
                ipv4:
                  enabled: true
                  address:
                  - ip: 192.168.18.67  
                    prefix-length: 25
                ipv6:
                  enabled: false
                  #address:
                  #- ip: 2620:52:0:1351:67c2:adb3:cfd6:81
                  #prefix-length: 64
            dns-resolver:
              config:
                search:
                - workload.bos2.lab
                server:
                - 192.168.18.9
            routes:
              config:
              - destination: 0.0.0.0/0
                next-hop-interface: enp1s0
                next-hop-address: 192.168.18.1
                table-id: 254