apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  name: "bos2ipv6"
  namespace: "bos2ipv6"
spec:
  baseDomain: "workload.bos2.lab"
  automatedCleaningMode: "metadata"
  pullSecretRef:
    name: "assisted-deployment-pull-secret-bos2ipv6"
  #clusterImageSetNameRef: "img4.11.7-x86-64-appsub"
  clusterImageSetNameRef: "img4.10.47-x86-64-appsub"
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCtSAUavTTr4dTvMOqZ/A6mg9q++qrVSNIu3vICnGUPpKGmQk4227TlaL9iwBkBqbGMvOaBZwn/b3URk/QE/El5ElzqaNNJxHqxWHGNKOJB49sVj5f57Usw07WyMy8CDy0Hk701jzvrdxqckfMEmMzWjE0C7Zpus6J3GyG3ANTYbSQGRtzdz7bcg05Xm0xCzfC/HAEF6Arz/cTv9k9rioiu1reV1qqq+FAlnKx3x/+XsG5cHMhnVuUnOU59p9pOh+v/nxq5Ysz/5iJrKNmJqkUAPShrfs3Kk2Z8TJVoEKoyyfme4uNAqBg2xZjnaPf8avfmc8uYzjHN7BA4w1fMw/mO71FCXkuxukttUeoqO2ARpofwzIeiH2wmJ7fKLaomETbZyIzYiVoZM2VKu1nPNmWOluqrpvNBnufWLpmRqWntmvT26IEGmlAjTz1HV0VZXVo+6viI3RQTJJXeZ7uTjCPz/uVsrv5U2BthWIkJ7OJEB0mcwbSJF5FOhML8dZ+/ODc= mjanardh@mjanardh.remote.csb"
  clusters:
  - clusterName: "bos2ipv6"
    networkType: "OVNKubernetes"
    #clusterType: "sno"
    #clusterProfile: "du"
    clusterLabels:
      group-du-sno: ""
      common: true
      sites : "bos2ipv6"
    clusterNetwork:
      - cidr: fd01::/48
        hostPrefix: 64
    machineNetwork:
      - cidr: 2600:52:7:18::/64
    serviceNetwork:
      - fd02::/112
    proxy:
      httpProxy: http://[2600:52:7:18::9]:3128
      httpsProxy: http://[2600:52:7:18::9]:3128
      noProxy: .workload.bos2.lab,wl-infra.workload.bos2.lab,192.168.18.128/25,192.168.18.0/25,6183
    additionalNTPSources:
      - 2.rhel.pool.ntp.org
    nodes:
      - hostName: "bos2ipv6.workload.bos2.lab"
        role: "master"
        automatedCleaningMode: "metadata"
        bmcAddress: "redfish-virtualmedia://2600:52:7:218::158:8080/redfish/v1/Systems/7d4f98ce-d5d6-4dcd-9b9e-a47a575d71aa"
        bmcCredentialsName: 
          name: "bos2ipv6-bmc-secret"
        bmc:
          disableCertificateVerification: "true"        
        bootMACAddress: "52:54:00:6c:3a:af"
        bootMode: "UEFI"
        rootDeviceHints:
          deviceName: "/dev/nvme0n1"
        cpuset: "0-1,32-33,62-63"
        proxy:
          httpProxy: http://[2600:52:7:18::9]:3128
          httpsProxy: http://[2600:52:7:18::9]:3128
          noProxy: .workload.bos2.lab,wl-infra.workload.bos2.lab,192.168.18.128/25,192.168.18.0/25,6183
        nodeNetwork:
          interfaces:
            - name: enp1s0
              macAddress: "52:54:00:6c:3a:af"
          config:
            interfaces:
              - name: enp1s0
                type: ethernet
                state: up
                macAddress: "52:54:00:6c:3a:af"
                #ipv4:
                  #enabled: True
                  #address:
                  #- ip: 192.168.18.67 
                    #prefix-length: 25
                ipv6:
                  enabled: True
                  address:
                  - ip: 2600:52:7:18::B7
                    prefix-length: 64
            dns-resolver:
              config:
                search:
                - workload.bos2.lab
                server:
                - 2600:52:7:18::9

            routes:
              config:
              #- destination: 0.0.0.0/0
                #next-hop-interface: enp1s0
                #next-hop-address: 192.168.18.1
                #table-id: 254
              - destination: ::/0
                next-hop-interface: enp1s0
                next-hop-address: 2600:52:7:18::1
                table-id: 254